// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZUcvl-Wr1Fe4v_vybdKnmf-UVDto9EV8',
    appId: '1:842732648028:web:33deab7f366cc2dd399899',
    messagingSenderId: '842732648028',
    projectId: 'todoapp-46618',
    authDomain: 'todoapp-46618.firebaseapp.com',
    storageBucket: 'todoapp-46618.firebasestorage.app',
    measurementId: 'G-268QP6JHLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfUQrSuppHSk4ukgindbMGe0H3RVJJFV8',
    appId: '1:842732648028:android:9dd57afdda5bba29399899',
    messagingSenderId: '842732648028',
    projectId: 'todoapp-46618',
    storageBucket: 'todoapp-46618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5AQWBEYeb24S3gZaaYqX0-3RV9LPz-I',
    appId: '1:842732648028:ios:f70ccd980fce076a399899',
    messagingSenderId: '842732648028',
    projectId: 'todoapp-46618',
    storageBucket: 'todoapp-46618.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5AQWBEYeb24S3gZaaYqX0-3RV9LPz-I',
    appId: '1:842732648028:ios:f70ccd980fce076a399899',
    messagingSenderId: '842732648028',
    projectId: 'todoapp-46618',
    storageBucket: 'todoapp-46618.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZUcvl-Wr1Fe4v_vybdKnmf-UVDto9EV8',
    appId: '1:842732648028:web:7ec9f4fdc5ee528a399899',
    messagingSenderId: '842732648028',
    projectId: 'todoapp-46618',
    authDomain: 'todoapp-46618.firebaseapp.com',
    storageBucket: 'todoapp-46618.firebasestorage.app',
    measurementId: 'G-VG27XQSY9B',
  );
}
