
// import 'package:flutter/material.dart';
// import 'package:flutter_bloc/flutter_bloc.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // generated by FlutterFire CLI
// import 'package:firebase_messaging/firebase_messaging.dart';
// import 'bloc/theme_bloc.dart';
// import 'bloc/theme_state.dart';
// import 'bloc/todo_bloc.dart';
// import 'bloc/todo_event.dart';
// import 'service/api_service.dart';
// import 'screens/landing_page.dart';
// import 'service/notification_service.dart';

// // void main() {
// //   final apiService = ApiService();
// //   runApp(MyApp(apiService: apiService));
// // }
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();

//   // Initialize Firebase
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//    // Initialize notifications
//   await NotificationService().init();
//     // Get FCM token
//   String? token = await FirebaseMessaging.instance.getToken();
//   print('FCM Device Token: $token');
 

//   final apiService = ApiService();
//   runApp(MyApp(apiService: apiService));
// }


// class MyApp extends StatelessWidget {
//   final ApiService apiService;
//   const MyApp({super.key, required this.apiService});

//   @override
//   Widget build(BuildContext context) {
//     return MultiBlocProvider(
//       providers: [
//         BlocProvider(create: (_) => ThemeBloc()),
//         BlocProvider(create: (_) => TodoBloc(apiService)..add(LoadTodos())),
//       ],
//       child: BlocBuilder<ThemeBloc, ThemeState>(
//         builder: (context, themeState) {
//           return MaterialApp(
//             debugShowCheckedModeBanner: false,
//             theme: themeState.themeData.copyWith(
//               elevatedButtonTheme: ElevatedButtonThemeData(
//                 style: ElevatedButton.styleFrom(
//                   backgroundColor: themeState.buttonColor,
//                   textStyle: TextStyle(
//                     fontFamily:
//                         themeState.isCustomFont ? 'Courier' : 'Roboto',
//                   ),
//                 ),
//               ),
//             ),
//             home: const LandingPage(),
//           );
//         },
//       ),
//     );
//   }
// }
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:firebase_in_app_messaging/firebase_in_app_messaging.dart';

import 'bloc/theme_bloc.dart';
import 'bloc/theme_state.dart';
import 'bloc/todo_bloc.dart';
import 'bloc/todo_event.dart';
import 'service/api_service.dart';
import 'screens/landing_page.dart';
import 'service/notification_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // ✅ Initialize Firebase In-App Messaging
final fiam = FirebaseInAppMessaging.instance;
fiam.setAutomaticDataCollectionEnabled(true); // optional, default is true
  // Initialize NotificationService
  await NotificationService().init();

  // Handle terminated state notification tap
  FirebaseMessaging.instance.getInitialMessage().then((message) {
    if (message != null) {
      MyApp.navigatorKey.currentState?.push(
        MaterialPageRoute(builder: (_) => const LandingPage()),
      );
    }
  });

  // Get FCM device token for testing
  String? token = await FirebaseMessaging.instance.getToken();
  print('FCM Device Token: $token');

  final apiService = ApiService();
  runApp(MyApp(apiService: apiService));
}

class MyApp extends StatelessWidget {
  // ✅ Static navigatorKey for global access
  static final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

  final ApiService apiService;
  const MyApp({super.key, required this.apiService});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => ThemeBloc()),
        BlocProvider(create: (_) => TodoBloc(apiService)..add(LoadTodos())),
      ],
      child: BlocBuilder<ThemeBloc, ThemeState>(
        builder: (context, themeState) {
          return MaterialApp(
            navigatorKey: navigatorKey, // ✅ Set navigatorKey
            debugShowCheckedModeBanner: false,
            theme: themeState.themeData.copyWith(
              elevatedButtonTheme: ElevatedButtonThemeData(
                style: ElevatedButton.styleFrom(
                  backgroundColor: themeState.buttonColor,
                  textStyle: TextStyle(
                    fontFamily: themeState.isCustomFont ? 'Courier' : 'Roboto',
                  ),
                ),
              ),
            ),
            home: const LandingPage(),
          );
        },
      ),
    );
  }
}
